# Homebrew Bundle
# https://docs.brew.sh/Manpage#bundle-subcommand
# cask 名は https://formulae.brew.sh/cask/ を参照

tap "stripe/stripe-cli"

# CLI
brew "bat"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "golangci-lint"
brew "buf"
brew "graphviz"
brew "hugo"
brew "libpq"
brew "mysql"
brew "neovim"
brew "pipx"
brew "plantuml"
brew "postgresql@18"
brew "python@3.14"
brew "rbenv"
brew "ripgrep"
brew "ruby-lsp"
brew "stripe"
brew "terraform"
brew "tmux"
brew "tree"
brew "wget"

# GUI / fonts
cask "aqua-voice"
cask "claude"
cask "clipy"
# https://formulae.brew.sh/cask/codex （ターミナル）
# npm の @openai/codex が /opt/homebrew/bin/codex を握っていると失敗する。
# cask の binary は他由来の symlink を上書きしない（--force でも不可）。先に npm 版を消すこと。
# `--overwrite` は formula 用で `--cask` と併用不可（Homebrew cmd/install.rb の conflicts）
cask "codex"
# https://formulae.brew.sh/cask/codex-app （デスクトップ。公式は deprecated）
cask "codex-app"
cask "cursor"
cask "dbeaver-community"
cask "docker-desktop"
cask "font-meslo-lg-nerd-font"
cask "font-source-code-pro"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "linearmouse"
cask "ngrok"
cask "rectangle"

# Cursor 拡張（このマシンの `cursor --list-extensions` から）
# brew bundle は code / codium / cursor の順で CLI を探す
# 参照: Homebrew bundle vscode_extension.rb
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.bookmarks"
vscode "anthropic.claude-code"
vscode "anysphere.remote-containers"
vscode "anysphere.remote-ssh"
vscode "asvetliakov.vscode-neovim"
vscode "bufbuild.vscode-buf"
vscode "devsense.composer-php-vscode"
vscode "devsense.intelli-php-vscode"
vscode "devsense.phptools-vscode"
vscode "devsense.profiler-php-vscode"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "hangxingliu.vscode-nginx-conf-hint"
vscode "hashicorp.terraform"
vscode "hediet.vscode-drawio"
vscode "humao.rest-client"
vscode "marp-team.marp-vscode"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.python"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.vscode-typescript-next"
vscode "mtxr.sqltools"
vscode "oderwat.indent-rainbow"
vscode "openai.chatgpt"
vscode "pkief.material-icon-theme"
vscode "postman.postman-for-vscode"
vscode "prisma.prisma"
vscode "qwtel.sqlite-viewer"
vscode "redhat.vscode-yaml"
vscode "shardulm94.trailing-spaces"
vscode "shopify.ruby-lsp"
vscode "tomi.xasnippets"
vscode "usernamehw.errorlens"
vscode "yzhang.markdown-all-in-one"
